### ISSUE TITLE
Missing file alchemy.translations

### ISSUE THREAD

**Issue by robinboening** [AlchemyCMS/alchemy_i18n#32]
PR https://github.com/AlchemyCMS/alchemy_cms/pull/1775 added Webpacker and also [removed the file](https://github.com/AlchemyCMS/alchemy_cms/pull/1775/files#diff-c391ec12f2a8d863f3298c886800050a977510fd398a73d56208d0d460c5393c) `app/assets/javascripts/alchemy/alchemy.translations.js.coffee` from the repo which is a dependency in `alchemy_i18n` due to the [require statement in the js files](https://github.com/AlchemyCMS/alchemy_i18n/blob/main/app/assets/javascripts/alchemy_i18n/de.js#L1).

This results in the following error when requiring those js locale files from `alchemy_i18n`

```
couldn't find file 'alchemy/alchemy.translations' with type 'application/javascript'
```

**Comment by afdev82** [comment]
Any news on this issue? I'm getting this error too when upgrading to Alchemy v5

**Comment by afdev82** [comment]
I was trying to find a solution, but the problem seems deeper.
If I just remove the require then I get

```
Alchemy.translations is undefined
```

I think the gem is not ready to work with Alchemy v5, because of the changes already linked by @robinboening .
I tried to export the translations in the global Alchemy object like before and use it in the translate function of the package @alchemy_cms/admin package, but I don't know if it's the right approach:

https://github.com/AlchemyCMS/alchemy_cms/pull/2114

**Comment by tvdeyen** [comment]
The solution in #34 should work without the `require` since it makes sure that `Alchemy.translations` is defined before mutating it.

**Comment by tvdeyen** [comment]
> The solution in #34 should work without the `require` since it makes sure that `Alchemy.translations` is defined before mutating it.

Ignore me. I now see what the problem was. Thanks for fixing.
