### ISSUE TITLE
Load the translations from the gem instead of copy

### ISSUE THREAD

**Issue by afdev82** [AlchemyCMS/alchemy_i18n#33]
Hi all,

I was using this gem to translate AlchemyCMS, but I noticed that it will be difficult to update the translations after the locales files are copied in my project.
If I edit the files afterwards, every time I wanted to get the new translations from the gem I would have to overwrite my local files and then modify them to just merge my translations and the new ones.
I think it would be easier to use the same approach of devise-i18n here: https://github.com/tigrish/devise-i18n/blob/master/lib/devise-i18n/railtie.rb
Just load the translations from the gem and allow the users to override some in their own project.
Usually I just override some translations from the devise-i18n gem and I take all the others from the gem.
When the translations are added / modified in the new version, I don't have to do anything, only update the gem to get the new translations.

What do you think about that?
If it's OK, I can work on that and submit a PR.

**Comment by tvdeyen** [comment]
We changed that on purpose because of memory consumption. Loading a lot of translations (most of them unused) into the memory is not very efficient. 

But, I think this was prematurely. It's not that many translations. 

Also, we could add a mechanic that only loads the locales into memory that actually are required by `I18n.available_locales` setting. 

Feel free to open a PR. We can discuss further thoughts on that.

**Comment by robinboening** [comment]
I'd also love to see that. I just ran into the same issue and would be happy if there was a solution as you described.
